/* AUTOGENERATED VIEW SOURCE FILE */
#include <cgicc/HTMLClasses.h>
#include <fleropp/HTMLStream.hpp>
#include <fleropp/HTMLLiterals.hpp>

#include "DemoView.hpp"

INIT_VIEW(DemoView)


void DemoView::get(const fleropp::io::RequestData& request) {
    
}
