/* AUTOGENERATED VIEW HEADER FILE */
#ifndef DEMOVIEW_HPP
#define DEMOVIEW_HPP

#include <fleropp/IView.hpp>

class DemoView : public IView<DemoView> {
  public:
    DemoView() = default;
    ~DemoView() = default;
    void get(const fleropp::io::RequestData& request);
};
#endif /* DEMOVIEW_HPP */
