#!/usr/bin/env bash

main() {
	RED='\033[0;31m'
	NC='\033[0m'
	bold=$(tput bold)
	normal=$(tput sgr0)

	FILE_NAME=""
	FULL_FILE=""
	DIRECTORY=""
	GET=""
	POST=""
	DELETE=""
	PUT=""
	[ "${#}" -eq 0 ] && usage && exit 1
	while getopts "gpudf:" opt; do
		case "${opt}" in
		  g) GET="1" ;;
		  p) POST="1" ;;
		  u) PUT="1" ;;
		  d) DELETE="1" ;;
		  h) usage && exit 1;;
		esac
	done
	shift "$(($OPTIND -1))"
	if [ $# -eq 1 ]; then 
		FILE_NAME=$(basename ${1})
		FULL_FILE=$1
		GET="1"
	fi

	if [ $# -gt 1 ]; then
		echo -e "${RED}${bold}ERROR: ${normal}${RED}To generate more than one file please use generate.sh${NC}" && usage && exit 2
	fi

	[ "$FILE_NAME" == "" ] && usage && exit 1


	cat <<EOF > $FULL_FILE.c 
/* AUTOGENERATED VIEW SOURCE FILE */
#include <cgicc/HTMLClasses.h>
#include <fleropp/HTMLStream.hpp>
#include <fleropp/HTMLLiterals.hpp>

#include "$FILE_NAME.h"

INIT_VIEW($FILE_NAME)

EOF
	[[ "$GET" == "1" ]] && cat <<EOF >> $FULL_FILE.c

void $FILE_NAME::get(const fleropp_io::RequestData& request) {

}
EOF

	[[ "$POST" == "1" ]] && cat <<EOF >> $FULL_FILE.c

void $FILE_NAME::post(const fleropp_io::RequestData& request) {

}
EOF
	[[ "$PUT" == "1" ]] && cat <<EOF >> $FULL_FILE.c

void $FILE_NAME::put(const fleropp_io::RequestData& request) {

}
EOF
	[[ "$DELETE" == "1" ]] && cat <<EOF >> $FULL_FILE.c

void $FILE_NAME::del(const fleropp_io::RequestData& request) {

}
EOF

	cat <<EOF > $FULL_FILE.h 
/* AUTOGENERATED VIEW HEADER FILE */
#ifndef $(echo $FILE_NAME | tr 'a-z' 'A-Z')_HPP
#define $(echo $FILE_NAME | tr 'a-z' 'A-Z')_HPP

#include <fleropp/IView.hpp>

class $FILE_NAME : public IView<$FILE_NAME> {
  public:
    $FILE_NAME() = default;
    ~$FILE_NAME() = default;
    void get(const fleropp_io::RequestData& request);
    void post(const fleropp_io::RequestData& request);
    void put(const fleroppio::RequestData& request)
    void del(const fleroppio::RequestData& request)
}
#endif /* $(echo $FILE_NAME | tr 'a-z' 'A-Z')_HPP */
EOF

}

usage () {
	cat <<EOF
usage: ${bold}$(basename ${0})${normal} [-gpud] filename

Tool to generate Fleropp Boilerplate, if no arguments are applied
GET function will be generated.

NOTE: if flag is used, only the flags will be generated

optional arguments:
	${bold}-g${normal}  Generate GET function
	${bold}-p${normal}  Generate POST function
	${bold}-u${normal}  Generate PUT function
	${bold}-d${normal}  Generate DELETE function
EOF
}
main $@

