services:
  apache2_fcgi:
    build: 
      context: .
    container_name: httpd_container
    command: /bin/sh -c "export SPDLOG_LEVEL=debug && /usr/sbin/apachectl start && /opt/fleropp_fpm/fleropp_fpm -p 50001 -w 20"
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - ./public-html:/var/www/html
      - ./etc/apache2.conf:/etc/apache2/apache2.conf
      - ./etc/fleropp:/etc/fleropp
      - ./etc/override:/etc/apache2/override
      - ../../fleropp_fpm/bin:/opt/fleropp_fpm
      - ../../fleropp_fpm/so:/usr/lib/fleropp
      - ../../fleropp_fpm/include:/usr/include/fleropp
